name: C++ Build and Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MinGW
        run: |
          choco install mingw

      - name: Compile loader.cpp to exe
        run: |
          g++ -o loader.exe loader.cpp

      - name: Compile roguerot.cpp to dll
        run: |
          g++ -shared -o roguerot.dll roguerot.cpp

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            loader.exe
            roguerot.dll
