name: C++ Build and Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install-packages: mingw-w64-x86_64-gcc

      - name: Compile loader.cpp to exe
        run: |
          gcc -o loader.exe loader.cpp

      - name: Compile roguerot.cpp to dll
        run: |
          gcc -shared -o roguerot.dll roguerot.cpp

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            loader.exe
            roguerot.dll
